/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.5 and Signal Processing Toolbox 8.1.
 * Generated on: 14-Apr-2019 16:12:50
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Window Type         : Chebyshev Type II
 * Filter Type         : IIR
 * Response Type       : Low Pass
 * Numerator Length    : 10
 * Denominator Length  : 10
 * Stable              : Yes
 * Linear Phase        : No
 * F-pass              : 10Hz
 * F-stop              : 20Hz
 * Group Delay         : about 40ms
 *
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\MATLAB\R2018b\extern\include\tmwtypes.h 
 */

typedef struct{
	double raw_value;
	double xbuf[10];
	double ybuf[10];
	double filtered_value;
}IIR_Filter_t;


typedef struct{
	double fir_raw_value;
	double fir_xbuf[361];
	double fir_ybuf[361];
	double fir_filtered_value;
}FIR_Filter_t;


#define BLACKMAN_LENGTH 101
typedef struct{
	double blm_raw_value;
	double blm_xbuf[BLACKMAN_LENGTH];
	double blm_ybuf[BLACKMAN_LENGTH];
	double blm_filtered_value;
}Blackman_Filter_t;


#define DELAY_MS 205 
typedef struct{
	double group_delay_raw_value;
	double group_delay_buffer[DELAY_MS];
}Group_Delay_t;
