/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.5 and Signal Processing Toolbox 8.1.
 * Generated on: 24-Apr-2019 19:12:50
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Window Type         : Butterworth
 * Filter Type         : IIR
 * Response Type       : Low Pass
 * Numerator Length    : 9
 * Denominator Length  : 9
 * Stable              : Yes
 * Linear Phase        : Yes
 * F-pass              : 15Hz
 * F-stop              : 40Hz
 * Group Delay         : 50ms
 *
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * D:\MATLAB\R2018b\extern\include\tmwtypes.h 
 */


#define N 9
typedef struct{
	double raw_value;
	double xbuf[N];
	double ybuf[N];
	double filtered_value;
}IIR_Filter_t;


typedef struct{
	double fir_raw_value;
	double fir_xbuf[361];
	double fir_ybuf[361];
	double fir_filtered_value;
}FIR_Filter_t;


#define BLACKMAN_LENGTH 101
typedef struct{
	double blm_raw_value;
	double blm_xbuf[BLACKMAN_LENGTH];
	double blm_ybuf[BLACKMAN_LENGTH];
	double blm_filtered_value;
}Blackman_Filter_t;


#define DELAY_MS 215
typedef struct{
	double group_delay_raw_value;
	double group_delay_buffer[DELAY_MS];
}Group_Delay_t;
